theme: dark #light/dark
#jwt_secret: 도커 시크릿으로 대체

default_redirection_url: https://google.com/ #where to redirect for a non-existent URL

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: info

totp: #2차인증으로 totp 사용
  issuer: domain.com #your authelia top-level domain
  period: 30
  skew: 1

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 5m

############################################
#  LDAP을 사용하면 아래 설정은 불필요하다.
#
#  file:
#    path: /config/users_database.yml #this is where your authorized users are stored
#    password:
#      algorithm: argon2id
#      iterations: 1
#      key_length: 32
#      salt_length: 16
#      memory: 1024
#      parallelism: 8
############################################

  # https://www.authelia.com/configuration/first-factor/ldap/
  ldap:
    implementation: custom
    url: ldaps://192.168.1.0/ # ldap이 설치된 시놀로지의 내부 아이피
    start_tls: false
    tls:
      server_name: synology
      skip_verify: true
      minimum_version: TLS1.2
    base_dn: dc=test,dc=syno,dc=com # 시놀로지 ldap 서버설정과 동일
    additional_users_dn: cn=users
    additional_groups_dn: cn=groups
    users_filter: (&({username_attribute}={input})(objectClass=person))
    groups_filter: (&(member={dn})(objectClass=posixGroup)) # 참고 www.ietf.org/rfc/rfc2307.txt
#    group_name_attribute: cn
    user: uid=root,cn=users,dc=test,dc=syno,dc=com # 시놀로지 bind_dn 설정
    password: 12345 # LDAP 서버 생성시 지정한 비번

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: 'auth.domain.com' #역방향 프록시로 지정한 authelia의 주소
      policy: bypass

    - domain:
      - '*.domain.com'
      - 'domain.com'
      policy: bypass
      networks:
        - 192.168.1.0/24

    - domain:
      - 'domain.com' #example domain to protect
      - 'www.domain.com'
      - 'traefik.domain.com'
      subject: 'group:administrators'
#      policy: one_factor
      policy: two_factor

    - domain:
      - 'domain.com' #example domain to protect
      - 'www.domain.com'
      subject: 'group:users'
      policy: one_factor

session:
  name: authelia_session
#  secret: # 도커 시크릿으로 대체
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: domain.com  # Should match whatever your root protected domain is

  redis: # redis 사용
    host: redis
    port: 6379

regulation:
  max_retries: 5
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3 #this is your databse. You could use a mysql database if you wanted, but we're going to use this one.
#  encryption_key: # 도커 시크릿으로 대체

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false

# smtp 설정을 한다면 이메일로 알림이 오지만, 설정하지 않는다면 파일로 작성된다
# 특히 맨처음 otp설정을 할때 이메일로 인증주소가 날라와야 하지만
# smtp설정을 안했다면 이 파일에 인증주소가 남겨지게 된다.
# 복사해서 붙여넣기 한후 otp인증과정을 계속 진행 할 수 있다.
notifier:
  filesystem:
    filename: /config/notification.txt

#이곳 설정은 oidc 부분에서 작성
#identity_providers:
#  oidc:

#사용할 생각 없음
#
#  smtp:
#    username: youremail@gmail.com #your email address
#    password: Y0uRp@55W0rD! #your email password
#    host: smtp.gmail.com #email smtp server
#    port: 587 #email smtp port
#    sender: youremail@gmail.com
#    identifier: localhost
#    subject: "[Authelia] {title}" #email subject
#    startup_check_address: youremail@gmail.com
#    disable_require_tls: false
#    disable_html_emails: false
#    tls:
#      skip_verify: false
#      minimum_version: TLS1.2